### Use REST Client extension https://marketplace.visualstudio.com/items?itemName=humao.rest-client 

### Get Active Drivers
GET http://localhost:7071/api/activedrivers

### Get Active Trips
GET http://localhost:7072/api/activetrips

### Get Passengers
GET http://localhost:7073/api/passengers
